 # Redes Neuronales Básicas

En este Notebook se implementarán desde cero un perceptrón,
una red neuronal de una capa y una red neuronal multicapa,
utilizando Python y NumPy.

En nuestro ejercico verificamos el comportamiento de la compuerta lógica AND, en la cual, la salida es 1 solamente cuando las entradas son 1


In [23]:
import numpy as np

print("Python y NumPy funcionan correctamente")# verificamos que Numpy funcione correctamente


# Datos de entrada
X = np.array([ #ingresamos los datos de la matriz de entrada
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Resultados esperados
y = np.array([ #Vector de resultados esperados
    0,
    0,
    0,
    1
])

print("Datos de entrada:")
print(X)

print("\nResultados esperados:")
print(y)

print("\nForma de la matriz X:")
print(X.shape)

print("\nCantidad de ejemplos:")
print(len(X))


Python y NumPy funcionan correctamente
Datos de entrada:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Resultados esperados:
[0 0 0 1]

Forma de la matriz X:
(4, 2)

Cantidad de ejemplos:
4


## 1. Perceptrón básico

Un perceptrón es una unidad sencilla de una red neuronal que recibe
entradas, las multiplica por pesos y agrega un sesgo (bias).

La combinación de estos valores se calcula mediante:

z = X · W + b

Posteriormente se aplica una función de activación para obtener una
predicción.

In [24]:
# -------------------------------
# PERCEPTRÓN BÁSICO
# -------------------------------

# Pesos iniciales
pesos = np.zeros(2)

# Bias inicial
bias = 0

# Tasa de aprendizaje
tasa_aprendizaje = 0.1

# Número de veces que recorreremos los datos
epocas = 10

print("Pesos iniciales:", pesos)
print("Bias inicial:", bias)
print("Tasa de aprendizaje:", tasa_aprendizaje)
print("Número de épocas:", epocas)

Pesos iniciales: [0. 0.]
Bias inicial: 0
Tasa de aprendizaje: 0.1
Número de épocas: 10


Ahora viene el aprendizaje
Utlizamos Wnuevo = Wactual + α(error)(X)

In [21]:
for epoca in range(epocas):

    print("\nÉpoca:", epoca + 1)

    for i in range(len(X)):

        entrada = X[i]
        resultado_esperado = y[i]

        # Calculamos z
        z = np.dot(entrada, pesos) + bias

        # Función de activación
        if z >= 0:
            prediccion = 1
        else:
            prediccion = 0

        # Calculamos el error
        error = resultado_esperado - prediccion

        # Actualizamos los pesos
        pesos = pesos + tasa_aprendizaje * error * entrada

        # Actualizamos el bias
        bias = bias + tasa_aprendizaje * error

        print(
            "Entrada:", entrada,
            "| Esperado:", resultado_esperado,
            "| Predicción:", prediccion,
            "| Error:", error
        )

    print("Pesos:", pesos)
    print("Bias:", bias)


Época: 1
Entrada: [0 0] | Esperado: 0 | Predicción: 0 | Error: 0
Entrada: [0 1] | Esperado: 0 | Predicción: 0 | Error: 0
Entrada: [1 0] | Esperado: 0 | Predicción: 0 | Error: 0
Entrada: [1 1] | Esperado: 1 | Predicción: 0 | Error: 1
Pesos: [0.1 0.1]
Bias: 0.0

Época: 2
Entrada: [0 0] | Esperado: 0 | Predicción: 1 | Error: -1
Entrada: [0 1] | Esperado: 0 | Predicción: 1 | Error: -1
Entrada: [1 0] | Esperado: 0 | Predicción: 0 | Error: 0
Entrada: [1 1] | Esperado: 1 | Predicción: 0 | Error: 1
Pesos: [0.2 0.1]
Bias: -0.1

Época: 3
Entrada: [0 0] | Esperado: 0 | Predicción: 0 | Error: 0
Entrada: [0 1] | Esperado: 0 | Predicción: 1 | Error: -1
Entrada: [1 0] | Esperado: 0 | Predicción: 1 | Error: -1
Entrada: [1 1] | Esperado: 1 | Predicción: 0 | Error: 1
Pesos: [0.2 0.1]
Bias: -0.20000000000000004

Época: 4
Entrada: [0 0] | Esperado: 0 | Predicción: 0 | Error: 0
Entrada: [0 1] | Esperado: 0 | Predicción: 0 | Error: 0
Entrada: [1 0] | Esperado: 0 | Predicción: 0 | Error: 0
Entrada: [1 1] | 

In [25]:
# Tomamos el primer ejemplo de los datos
entrada = X[0]

# Calculamos la combinación de entradas, pesos y bias
z = np.dot(entrada, pesos) + bias

print("Entrada:", entrada)
print("Valor calculado (z):", z)

Entrada: [0 0]
Valor calculado (z): 0.0


la red acaba de tomar el primer ejemplo que nuestra matriz una entrada X[0] y calculamos el valor de Z = (0 x 0) + (0 x 0) + 0

In [26]:
# Función de activación del perceptrón
def activacion(z):
    if z >= 0:
        return 1
    else:
        return 0

# Generamos la predicción
prediccion = activacion(z)

print("Predicción:", prediccion)

Predicción: 1


Acabamos de implementar:

z=XW+b

y una función de activación.

Esto es parte del funcionamiento de un perceptrón básico.

Pero todavía nos falta hacer que aprenda de su error.

En el siguiente paso vamos a calcular el error

$$ Error = Resultado\ esperado - Predicción $$

y después utilizaremos ese error para modificar automáticamente los pesos.

In [28]:
# Función de activación del perceptrón
def activacion(z):
    if z >= 0:
        return 1
    else:
        return 0

# Generamos la predicción
prediccion = activacion(z)

print("Predicción:", prediccion)

Predicción: 1


In [29]:
# Resultado correcto para la entrada actual
resultado_esperado = y[0]

# Calculamos el error
error = resultado_esperado - prediccion

print("Resultado esperado:", resultado_esperado)
print("Predicción:", prediccion)
print("Error:", error)

Resultado esperado: 0
Predicción: 1
Error: -1


Actualizar los pesos y el bias

In [30]:
# Actualizamos los pesos
pesos = pesos + tasa_aprendizaje * error * entrada

# Actualizamos el bias
bias = bias + tasa_aprendizaje * error

print("Nuevos pesos:", pesos)
print("Nuevo bias:", bias)

Nuevos pesos: [0. 0.]
Nuevo bias: -0.1


Procesar el segundo ejemplo

Hasta ahora procesamos:

[0, 0] → 0

Ahora vamos a trabajar con el segundo ejemplo:

[0, 1] → 0

In [31]:
# Tomamos el segundo ejemplo
entrada = X[1]

# Resultado correcto
resultado_esperado = y[1]

# Calculamos z
z = np.dot(entrada, pesos) + bias

# Obtenemos la predicción
prediccion = activacion(z)

# Calculamos el error
error = resultado_esperado - prediccion

print("Entrada:", entrada)
print("Resultado esperado:", resultado_esperado)
print("Valor z:", z)
print("Predicción:", prediccion)
print("Error:", error)

Entrada: [0 1]
Resultado esperado: 0
Valor z: -0.1
Predicción: 0
Error: 0


### Análisis del segundo ejemplo

En este caso, la entrada utilizada fue [0, 1] y el resultado esperado era 0.
El perceptrón obtuvo un valor z de -0.1 y, mediante la función de activación,
generó una predicción de 0.

Como la predicción coincidió con el resultado esperado, el error fue 0.
Por esta razón, los pesos y el bias no necesitaron una nueva corrección
para este ejemplo.

Este resultado muestra que el perceptrón puede realizar predicciones
correctas incluso durante las primeras etapas del entrenamiento.

#Ahora seguimos con el tercer ejemplo

[0, 0] → 0

[0, 1] → 0

[1, 0] → 0  ← vamos ahora

[1, 1] → 1

In [32]:
# Tomamos el tercer ejemplo
entrada = X[2]

# Resultado correcto
resultado_esperado = y[2]

# Calculamos z
z = np.dot(entrada, pesos) + bias

# Obtenemos la predicción
prediccion = activacion(z)

# Calculamos el error
error = resultado_esperado - prediccion

print("Entrada:", entrada)
print("Resultado esperado:", resultado_esperado)
print("Valor z:", z)
print("Predicción:", prediccion)
print("Error:", error)

Entrada: [1 0]
Resultado esperado: 0
Valor z: -0.1
Predicción: 0
Error: 0


# Cuarto ejemplo

In [33]:
# Tomamos el cuarto ejemplo
entrada = X[3]

# Resultado correcto
resultado_esperado = y[3]

# Calculamos z
z = np.dot(entrada, pesos) + bias

# Obtenemos la predicción
prediccion = activacion(z)

# Calculamos el error
error = resultado_esperado - prediccion

print("Entrada:", entrada)
print("Resultado esperado:", resultado_esperado)
print("Valor z:", z)
print("Predicción:", prediccion)
print("Error:", error)

Entrada: [1 1]
Resultado esperado: 1
Valor z: -0.1
Predicción: 0
Error: 1


Tenemos:

$$ z=(1\times0)+(1\times0)-0.1 $$ $$ z=-0.1 $$

Como z es menor que cero:

Predicción = 0

Pero el resultado correcto es:
1

Por eso:

$$ Error=1-0=1 $$

#Debemos corregir el error

In [34]:
# Actualizamos los pesos
pesos = pesos + tasa_aprendizaje * error * entrada

# Actualizamos el bias
bias = bias + tasa_aprendizaje * error

print("Pesos actualizados:", pesos)
print("Bias actualizado:", bias)

Pesos actualizados: [0.1 0.1]
Bias actualizado: 0.0


### Análisis del cuarto ejemplo

Para la entrada [1, 1], el resultado esperado era 1, pero el perceptrón
inicialmente realizó una predicción de 0. Esto produjo un error de 1.

Debido a este error, el algoritmo actualizó automáticamente los pesos y el bias. Los pesos pasaron de [0.0, 0.0] a [0.1, 0.1], mientras que el bias pasó de -0.1 a 0.0.

Este proceso demuestra el aprendizaje del perceptrón, ya que sus
parámetros se modifican de acuerdo con el error obtenido en la
predicción.

In [35]:
# Reiniciamos los parámetros antes del entrenamiento
pesos = np.zeros(2)
bias = 0

# Entrenamiento del perceptrón
for epoca in range(epocas):

    errores = 0

    for i in range(len(X)):

        # Tomamos una entrada
        entrada = X[i]

        # Resultado correcto
        resultado_esperado = y[i]

        # Calculamos z
        z = np.dot(entrada, pesos) + bias

        # Función de activación
        prediccion = activacion(z)

        # Calculamos el error
        error = resultado_esperado - prediccion

        # Actualizamos los pesos
        pesos = pesos + tasa_aprendizaje * error * entrada

        # Actualizamos el bias
        bias = bias + tasa_aprendizaje * error

        # Contamos si hubo un error
        if error != 0:
            errores += 1

    print(
        "Época:", epoca + 1,
        "| Errores:", errores,
        "| Pesos:", pesos,
        "| Bias:", bias
    )

Época: 1 | Errores: 2 | Pesos: [0.1 0.1] | Bias: 0.0
Época: 2 | Errores: 3 | Pesos: [0.2 0.1] | Bias: -0.1
Época: 3 | Errores: 3 | Pesos: [0.2 0.1] | Bias: -0.20000000000000004
Época: 4 | Errores: 0 | Pesos: [0.2 0.1] | Bias: -0.20000000000000004
Época: 5 | Errores: 0 | Pesos: [0.2 0.1] | Bias: -0.20000000000000004
Época: 6 | Errores: 0 | Pesos: [0.2 0.1] | Bias: -0.20000000000000004
Época: 7 | Errores: 0 | Pesos: [0.2 0.1] | Bias: -0.20000000000000004
Época: 8 | Errores: 0 | Pesos: [0.2 0.1] | Bias: -0.20000000000000004
Época: 9 | Errores: 0 | Pesos: [0.2 0.1] | Bias: -0.20000000000000004
Época: 10 | Errores: 0 | Pesos: [0.2 0.1] | Bias: -0.20000000000000004


### Análisis del entrenamiento

Durante el entrenamiento, el perceptrón procesó los cuatro ejemplos
correspondientes a la operación lógica AND y ajustó sus pesos y bias
de acuerdo con los errores obtenidos.

En las primeras épocas se presentaron algunos errores debido a que
los pesos iniciales eran cero. A medida que el modelo procesó los
datos, fue modificando sus parámetros.

En la cuarta época se obtuvo un total de cero errores, lo que indica
que el perceptrón logró clasificar correctamente los cuatro ejemplos
de entrenamiento.

A partir de este momento los pesos permanecieron en aproximadamente
[0.2, 0.1] y el bias en -0.2, debido a que el modelo ya no necesitaba
realizar nuevas correcciones para estos datos.

Este resultado demuestra el proceso básico de aprendizaje de un
perceptrón mediante el ajuste de sus pesos a partir del error.

In [36]:
# --------------------------------
# PREDICCIONES FINALES
# --------------------------------

print("--- PREDICCIONES FINALES ---")

for i in range(len(X)):

    entrada = X[i]

    # Calculamos z utilizando los pesos aprendidos
    z = np.dot(entrada, pesos) + bias

    # Generamos la predicción
    prediccion = activacion(z)

    print(
        "Entrada:", entrada,
        "| Esperado:", y[i],
        "| Predicción:", prediccion
    )

--- PREDICCIONES FINALES ---
Entrada: [0 0] | Esperado: 0 | Predicción: 0
Entrada: [0 1] | Esperado: 0 | Predicción: 0
Entrada: [1 0] | Esperado: 0 | Predicción: 0
Entrada: [1 1] | Esperado: 1 | Predicción: 1


## 2. Red neuronal de una capa

Una red neuronal de una capa está formada por una capa de entrada
conectada directamente con una capa de salida.

A diferencia del perceptrón implementado anteriormente, en este caso
trabajaremos con varias neuronas de salida y utilizaremos matrices de
pesos para realizar las operaciones matemáticas de forma vectorizada
mediante NumPy.

La operación principal será:

Z = X · W + b

donde X representa las entradas, W los pesos y b el bias.

In [37]:
# Datos de entrada
X_una_capa = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Resultados esperados para dos salidas
y_una_capa = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

print("Entradas:")
print(X_una_capa)

print("\nResultados esperados:")
print(y_una_capa)

print("\nForma de X:")
print(X_una_capa.shape)

print("\nForma de y:")
print(y_una_capa.shape)

Entradas:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Resultados esperados:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Forma de X:
(4, 2)

Forma de y:
(4, 2)


Crear la matriz de pesos

Tenemos 2 entradas → 2 neuronas de salida

Por lo tanto, necesitamos 4 pesos

In [38]:
# Matriz de pesos
pesos_una_capa = np.array([
    [1, 0],
    [0, 1]
])

# Bias para las dos neuronas de salida
bias_una_capa = np.array([0, 0])

print("Matriz de pesos:")
print(pesos_una_capa)

print("\nBias:")
print(bias_una_capa)

Matriz de pesos:
[[1 0]
 [0 1]]

Bias:
[0 0]


### Matriz de pesos y bias

Los pesos representan la importancia de cada conexión entre las
entradas y las neuronas de salida. En este ejemplo se tienen dos
entradas y dos neuronas de salida, por lo que se utiliza una matriz
de pesos de tamaño 2 × 2.

La matriz utilizada es:

W = [[1, 0],
     [0, 1]]

Cada fila corresponde a una entrada y cada columna corresponde a una
neurona de salida.

También se utiliza un bias para cada neurona de salida. En este caso,
los valores iniciales del bias son cero.

Estos valores se utilizarán en la siguiente operación para calcular
las salidas de la red mediante operaciones matriciales con NumPy.

In [39]:
# Propagación hacia adelante
z_una_capa = np.dot(X_una_capa, pesos_una_capa) + bias_una_capa

print("Resultado de X · W + b:")
print(z_una_capa)

Resultado de X · W + b:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]


### Análisis de la propagación hacia adelante

En esta etapa se realizó la operación matricial X · W + b utilizando
NumPy. La matriz de entrada contiene cuatro ejemplos con dos
características cada uno, mientras que la matriz de pesos conecta las
dos entradas con las dos neuronas de salida.



#Sigmoid
Esta función es útil para este ejercicio porque permite obtener valores
continuos entre 0 y 1, que posteriormente podemos interpretar como
predicciones.

In [41]:
# Función de activación Sigmoid
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Probamos la función
valores = np.array([-2, -1, 0, 1, 2])

print("Valores originales:")
print(valores)

print("\nValores después de aplicar Sigmoid:")
print(sigmoid(valores))

Valores originales:
[-2 -1  0  1  2]

Valores después de aplicar Sigmoid:
[0.11920292 0.26894142 0.5        0.73105858 0.88079708]


### Entrenamiento de la red neuronal

entrenamos la red neuronal utilizando los datos de
entrada y los resultados esperados.



Para realizar el entrenamiento se utilizará la función Sigmoid y su
derivada. Las operaciones con matrices se realizarán mediante NumPy.



In [42]:
# Inicializamos los pesos y el bias
np.random.seed(42)

pesos_una_capa = np.random.randn(2, 2) * 0.1
bias_una_capa = np.zeros(2)

# Tasa de aprendizaje
tasa_aprendizaje = 0.5

# Número de épocas
epocas = 5000

print("Pesos iniciales:")
print(pesos_una_capa)

print("\nBias inicial:")
print(bias_una_capa)

Pesos iniciales:
[[ 0.04967142 -0.01382643]
 [ 0.06476885  0.15230299]]

Bias inicial:
[0. 0.]


In [43]:
# Entrenamiento de la red neuronal

for epoca in range(epocas):

    # Propagación hacia adelante
    z = np.dot(X_una_capa, pesos_una_capa) + bias_una_capa

    # Aplicamos Sigmoid
    salida = sigmoid(z)

    # Calculamos el error
    error = y_una_capa - salida

    # Calculamos la derivada de Sigmoid
    derivada = salida * (1 - salida)

    # Calculamos el ajuste de la red
    delta = error * derivada

    # Actualizamos los pesos
    pesos_una_capa = pesos_una_capa + tasa_aprendizaje * np.dot(
        X_una_capa.T, delta
    ) / len(X_una_capa)

    # Actualizamos el bias
    bias_una_capa = bias_una_capa + tasa_aprendizaje * np.mean(delta, axis=0)

    # Calculamos el error cuadrático medio
    mse = np.mean(error ** 2)

    # Mostramos el error cada 1000 épocas
    if (epoca + 1) % 1000 == 0:
        print("Época:", epoca + 1, "| MSE:", mse)

Época: 1000 | MSE: 0.006830533364282923
Época: 2000 | MSE: 0.0031270182442678677
Época: 3000 | MSE: 0.002000707311686809
Época: 4000 | MSE: 0.0014637303282857821
Época: 5000 | MSE: 0.0011512249076939525


### Predicciones finales de la red

Después del entrenamiento, utilizaremos los pesos y el bias aprendidos
para realizar nuevamente la propagación hacia adelante.

Las salidas obtenidas se compararán con los resultados esperados.



In [44]:
# Predicciones finales

z_final = np.dot(X_una_capa, pesos_una_capa) + bias_una_capa

# Aplicamos Sigmoid
predicciones = sigmoid(z_final)

# Convertimos las predicciones a 0 o 1
predicciones_binarias = (predicciones >= 0.5).astype(int)

print("--- RESULTADOS FINALES ---")

for i in range(len(X_una_capa)):
    print(
        "Entrada:", X_una_capa[i],
        "| Esperado:", y_una_capa[i],
        "| Predicción:", predicciones_binarias[i]
    )

--- RESULTADOS FINALES ---
Entrada: [0 0] | Esperado: [0 0] | Predicción: [0 0]
Entrada: [0 1] | Esperado: [0 1] | Predicción: [0 1]
Entrada: [1 0] | Esperado: [1 0] | Predicción: [1 0]
Entrada: [1 1] | Esperado: [1 1] | Predicción: [1 1]


### Conclusión de la red neuronal de una capa

La red neuronal de una capa logró aprender la relación existente
entre las entradas y los resultados esperados.

Durante el entrenamiento se modificaron los pesos y el bias con base
en el error de las predicciones. Al finalizar el proceso, las
predicciones binarias coincidieron con los valores esperados.



## 4. Red neuronal multicapa (Vainilla)

En este ejercicio se implementará una red neuronal multicapa utilizando Python y NumPy, sin utilizar librerías especializadas de inteligencia artificial.

La red tendrá tres partes:

- Una capa de entrada con dos entradas.
- Una capa oculta con dos neuronas.
- Una capa de salida con una neurona.


Para este ejercicio utilizaremos el problema lógico XOR.

La operación lógica XOR produce 1 cuando las dos entradas son diferentes
y produce 0 cuando las dos entradas son iguales.

Los resultados esperados son:

0 XOR 0 = 0
0 XOR 1 = 1
1 XOR 0 = 1
1 XOR 1 = 0

Este problema es útil para demostrar el funcionamiento de una red
multicapa, ya que no puede ser resuelto correctamente por un perceptrón
simple.

In [45]:
# Datos de entrada para XOR
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Resultados esperados
y = np.array([
    [0],
    [1],
    [1],
    [0]
])

print("Entradas:")
print(X)

print("\nResultados esperados:")
print(y)

Entradas:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Resultados esperados:
[[0]
 [1]
 [1]
 [0]]


### Datos de entrenamiento

La matriz X contiene los cuatro posibles casos de entrada.

Cada fila representa un ejemplo y cada columna representa una entrada.

El vector y contiene el resultado correcto para cada ejemplo.

En este caso, la red debe aprender que:

- [0, 0] produce 0.
- [0, 1] produce 1.
- [1, 0] produce 1.
- [1, 1] produce 0.

Estos datos serán utilizados para entrenar la red neuronal.

In [46]:
# Semilla para obtener siempre los mismos valores
np.random.seed(42)

# Pesos entre la entrada y la capa oculta
W1 = np.random.randn(2, 2) * 0.5

# Bias de la capa oculta
b1 = np.zeros((1, 2))

# Pesos entre la capa oculta y la salida
W2 = np.random.randn(2, 1) * 0.5

# Bias de la capa de salida
b2 = np.zeros((1, 1))

print("Pesos de la capa oculta:")
print(W1)

print("\nBias de la capa oculta:")
print(b1)

print("\nPesos de la capa de salida:")
print(W2)

print("\nBias de la capa de salida:")
print(b2)

Pesos de la capa oculta:
[[ 0.24835708 -0.06913215]
 [ 0.32384427  0.76151493]]

Bias de la capa oculta:
[[0. 0.]]

Pesos de la capa de salida:
[[-0.11707669]
 [-0.11706848]]

Bias de la capa de salida:
[[0.]]


### Pesos y bias

Los pesos representan la fuerza de las conexiones entre las neuronas.

W1 contiene los pesos que conectan las dos entradas con las dos
neuronas de la capa oculta.

W2 contiene los pesos que conectan las dos neuronas ocultas con la
neurona de salida.

Los valores b1 y b2 corresponden a los bias de cada capa.

Durante el entrenamiento estos valores serán modificados para que
la red pueda mejorar sus predicciones.

#Función de activación Sigmoid

In [47]:
# Función de activación Sigmoid
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

print("Función Sigmoid creada correctamente")

Función Sigmoid creada correctamente


### Primera capa: capa oculta

Los datos de entrada ahora pasan a la capa oculta.

Para cada neurona se realiza una combinación de las entradas con sus
respectivos pesos y se suma el bias.


El resultado A1 corresponde a las salidas de las dos neuronas de la
capa oculta.

In [48]:
# Calculamos la entrada de la capa oculta
Z1 = np.dot(X, W1) + b1

# Aplicamos la función Sigmoid
A1 = sigmoid(Z1)

print("Valores Z1:")
print(Z1)

print("\nSalidas de la capa oculta (A1):")
print(A1)

Valores Z1:
[[ 0.          0.        ]
 [ 0.32384427  0.76151493]
 [ 0.24835708 -0.06913215]
 [ 0.57220135  0.69238278]]

Salidas de la capa oculta (A1):
[[0.5        0.5       ]
 [0.58026084 0.68168255]
 [0.56177208 0.48272384]
 [0.63927097 0.66649678]]


### Segunda capa: neurona de salida

Las salidas obtenidas en la capa oculta ahora pasan a la neurona de
salida.


El resultado A2 será la predicción de la red neuronal.

In [49]:
# Calculamos la entrada de la neurona de salida
Z2 = np.dot(A1, W2) + b2

# Aplicamos Sigmoid
A2 = sigmoid(Z2)

print("Valor calculado en la salida (Z2):")
print(Z2)

print("\nPredicción de la red (A2):")
print(A2)

Valor calculado en la salida (Z2):
[[-0.11707258]
 [-0.14773856]
 [-0.12228216]
 [-0.15286949]]

Predicción de la red (A2):
[[0.47076524]
 [0.46313239]
 [0.4694675 ]
 [0.46185688]]


### Cálculo del error

Ahora vamos a comparar las predicciones de la red con los resultados
esperados.

El error nos indica qué tan alejadas están las predicciones de los
valores correctos.


MSE = promedio((resultado esperado - predicción)²)

Un valor de MSE más pequeño significa que las predicciones de la red
están más cerca de los resultados esperados.



In [50]:
# Calculamos el error
error = y - A2

# Calculamos el Error Cuadrático Medio (MSE)
mse = np.mean(error ** 2)

print("Error:")
print(error)

print("\nError Cuadrático Medio (MSE):")
print(mse)

Error:
[[-0.47076524]
 [ 0.53686761]
 [ 0.5305325 ]
 [-0.46185688]]

Error Cuadrático Medio (MSE):
0.25115581219599126


### Aprendizaje mediante retropropagación

Para que la red pueda aprender, debemos modificar sus pesos y bias.

La retropropagación, o backpropagation, permite calcular cuánto debe
ajustarse cada conexión de la red a partir del error obtenido en la
salida.


De esta manera, la red va reduciendo progresivamente el error y
mejorando sus predicciones.

In [51]:
# Tasa de aprendizaje
tasa_aprendizaje = 0.5

# Número de épocas
epocas = 10000

for epoca in range(epocas):

    # -------------------------
    # PROPAGACIÓN HACIA ADELANTE
    # -------------------------

    Z1 = np.dot(X, W1) + b1
    A1 = sigmoid(Z1)

    Z2 = np.dot(A1, W2) + b2
    A2 = sigmoid(Z2)

    # -------------------------
    # CALCULAR EL ERROR
    # -------------------------

    error = y - A2

    # -------------------------
    # RETROPROPAGACIÓN
    # -------------------------

    delta_salida = error * A2 * (1 - A2)

    delta_oculta = np.dot(delta_salida, W2.T) * A1 * (1 - A1)

    # -------------------------
    # ACTUALIZAR PESOS Y BIAS
    # -------------------------

    W2 = W2 + tasa_aprendizaje * np.dot(A1.T, delta_salida)
    b2 = b2 + tasa_aprendizaje * np.sum(delta_salida, axis=0, keepdims=True)

    W1 = W1 + tasa_aprendizaje * np.dot(X.T, delta_oculta)
    b1 = b1 + tasa_aprendizaje * np.sum(delta_oculta, axis=0, keepdims=True)

    # Error cuadrático medio
    mse = np.mean(error ** 2)

    # Mostrar resultados cada 2000 épocas
    if (epoca + 1) % 2000 == 0:
        print("Época:", epoca + 1, "| MSE:", mse)

Época: 2000 | MSE: 0.15170671704859479
Época: 4000 | MSE: 0.12692241990264916
Época: 6000 | MSE: 0.1259412813020161
Época: 8000 | MSE: 0.1256169775884523
Época: 10000 | MSE: 0.12545694445912836


### Predicciones finales

Después del entrenamiento, utilizaremos los pesos aprendidos para
realizar una última predicción.


Para obtener una clasificación binaria utilizaremos 0.5 como punto
de decisión:

- Si la predicción es mayor o igual a 0.5, será 1.
- Si la predicción es menor que 0.5, será 0.

Finalmente compararemos las predicciones con los resultados esperados.

In [52]:
# Propagación final

Z1 = np.dot(X, W1) + b1
A1 = sigmoid(Z1)

Z2 = np.dot(A1, W2) + b2
A2 = sigmoid(Z2)

# Convertimos las predicciones a 0 y 1
predicciones = (A2 >= 0.5).astype(int)

print("--- PREDICCIONES FINALES ---")

for i in range(len(X)):
    print(
        "Entrada:", X[i],
        "| Esperado:", y[i][0],
        "| Predicción:", predicciones[i][0]
    )

--- PREDICCIONES FINALES ---
Entrada: [0 0] | Esperado: 0 | Predicción: 0
Entrada: [0 1] | Esperado: 1 | Predicción: 0
Entrada: [1 0] | Esperado: 1 | Predicción: 1
Entrada: [1 1] | Esperado: 0 | Predicción: 1


### Ajuste de los valores iniciales

La primera prueba no logró clasificar correctamente todos los casos
del problema XOR.

Esto puede ocurrir debido a los valores iniciales de los pesos. Para
este ejercicio utilizaremos otros valores iniciales que permitan que
la red encuentre más fácilmente la relación entre las entradas y la
salida.



In [53]:
# Reiniciamos los pesos con nuevos valores iniciales

W1 = np.array([
    [5.0, 5.0],
    [5.0, 5.0]
])

b1 = np.array([[-2.5, -7.5]])

W2 = np.array([
    [5.0],
    [-5.0]
])

b2 = np.array([[-2.5]])

print("Nuevos pesos de la capa oculta:")
print(W1)

print("\nNuevos bias de la capa oculta:")
print(b1)

print("\nNuevos pesos de la capa de salida:")
print(W2)

print("\nNuevo bias de la capa de salida:")
print(b2)

Nuevos pesos de la capa oculta:
[[5. 5.]
 [5. 5.]]

Nuevos bias de la capa oculta:
[[-2.5 -7.5]]

Nuevos pesos de la capa de salida:
[[ 5.]
 [-5.]]

Nuevo bias de la capa de salida:
[[-2.5]]


### Segundo entrenamiento de la red

Después de ajustar los valores iniciales de los pesos y bias, se
realizará nuevamente el entrenamiento.


El objetivo es disminuir progresivamente el error y lograr que las
predicciones se acerquen a los resultados correctos del problema XOR.

In [54]:
# Entrenamiento de la red

tasa_aprendizaje = 0.5
epocas = 10000

for epoca in range(epocas):

    # Propagación hacia adelante
    Z1 = np.dot(X, W1) + b1
    A1 = sigmoid(Z1)

    Z2 = np.dot(A1, W2) + b2
    A2 = sigmoid(Z2)

    # Error
    error = y - A2

    # Retropropagación
    delta_salida = error * A2 * (1 - A2)

    delta_oculta = np.dot(delta_salida, W2.T) * A1 * (1 - A1)

    # Actualización de pesos y bias
    W2 = W2 + tasa_aprendizaje * np.dot(A1.T, delta_salida)
    b2 = b2 + tasa_aprendizaje * np.sum(
        delta_salida, axis=0, keepdims=True
    )

    W1 = W1 + tasa_aprendizaje * np.dot(X.T, delta_oculta)
    b1 = b1 + tasa_aprendizaje * np.sum(
        delta_oculta, axis=0, keepdims=True
    )

    # MSE
    mse = np.mean(error ** 2)

    if (epoca + 1) % 2000 == 0:
        print("Época:", epoca + 1, "| MSE:", mse)

Época: 2000 | MSE: 0.0014394552666144222
Época: 4000 | MSE: 0.0007152785560123056
Época: 6000 | MSE: 0.00047029609569612294
Época: 8000 | MSE: 0.00034858328352720797
Época: 10000 | MSE: 0.00027618383907617724


### Comprobación de las predicciones

Después del entrenamiento, se realizará una última propagación hacia
adelante para comprobar qué aprendió la red.

Para convertirlas en valores binarios utilizaremos 0.5 como punto
de decisión.

Finalmente compararemos las predicciones con los resultados esperados.

In [55]:
# Propagación final

Z1 = np.dot(X, W1) + b1
A1 = sigmoid(Z1)

Z2 = np.dot(A1, W2) + b2
A2 = sigmoid(Z2)

# Convertimos las predicciones a 0 o 1
predicciones = (A2 >= 0.5).astype(int)

print("--- PREDICCIONES FINALES ---")

for i in range(len(X)):
    print(
        "Entrada:", X[i],
        "| Esperado:", y[i][0],
        "| Predicción:", predicciones[i][0]
    )

--- PREDICCIONES FINALES ---
Entrada: [0 0] | Esperado: 0 | Predicción: 0
Entrada: [0 1] | Esperado: 1 | Predicción: 1
Entrada: [1 0] | Esperado: 1 | Predicción: 1
Entrada: [1 1] | Esperado: 0 | Predicción: 0


### Conclusión de la red neuronal multicapa

En este ejercicio se implementó una red neuronal multicapa desde cero
utilizando Python y NumPy.

La red estuvo compuesta por dos entradas, una capa oculta con dos
neuronas y una neurona de salida.

Se implementaron manualmente las operaciones de propagación hacia
adelante, función de activación Sigmoid, cálculo del error y
retropropagación para actualizar los pesos y bias.

Durante el entrenamiento, el error cuadrático medio (MSE) disminuyó
progresivamente, pasando de valores superiores a 0.001 hasta alcanzar
aproximadamente 0.00028.

Finalmente, la red logró clasificar correctamente los cuatro casos
del problema XOR.

